import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
const host=document.querySelector('#view'), status=document.querySelector('#status'), nodes=document.querySelector('#nodes');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(devicePixelRatio);renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;host.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x11151b);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.02,5000);const controls=new OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight(0xddeeff,0x332211,2));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(-4,6,8);scene.add(sun);scene.add(new THREE.AxesHelper(2));
let root=null, selected=null;function fit(object=root,view='iso'){if(!object)return;const b=new THREE.Box3().setFromObject(object),c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()),r=Math.max(s.x,s.y,s.z,1);controls.target.copy(c);const dirs={iso:new THREE.Vector3(-1,.75,1),north:new THREE.Vector3(0,.25,1),top:new THREE.Vector3(0,1,0.001)};camera.position.copy(c).add(dirs[view].normalize().multiplyScalar(r*2.2));camera.near=Math.max(.01,r/1000);camera.far=r*20;camera.updateProjectionMatrix();controls.update()}
function install(gltf){if(root)scene.remove(root);root=gltf.scene;scene.add(root);nodes.innerHTML='<option>Select node</option>';const seen=new Set();root.traverse(o=>{const id=o.userData?.node_id;if(id&&!seen.has(id)){seen.add(id);const x=document.createElement('option');x.value=id;x.textContent=id;nodes.append(x)}});status.textContent=`Loaded ${seen.size} semantic nodes. glTF is +Y up; labels use canonical mapping: east +X, north -Z, up +Y.`;fit()}
const loader=new GLTFLoader();document.querySelector('#file').onchange=e=>{const f=e.target.files[0];if(f)loader.load(URL.createObjectURL(f),install,undefined,x=>status.innerHTML=`<span class=error>${x.message}</span>`)};
nodes.onchange=()=>{selected=null;root?.traverse(o=>{if(o.userData?.node_id===nodes.value)selected=o});fit(selected)};document.querySelector('#fit').onclick=()=>fit(selected||root,document.querySelector('#camera').value);document.querySelector('#camera').onchange=e=>fit(selected||root,e.target.value);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});
